Wp 1233 ring group user timeout
wazo-platform/wazo-agid pull request #140
Opened 2024-01-29 19:26 UTC by DrPyser

2024-01-30 15:02 UTC, pc-m requested changes

2024-01-30 15:02 UTC, pc-m commented on wazo_agid/handlers/groupfeatures.py
> +        logger.debug('%s=%s', dialplan_variables.DESTINATION_ID, dst_id)
This logger should be removed

2024-02-02 14:57 UTC, sboily requested changes

2024-02-02 14:57 UTC, sboily commented on wazo_agid/handlers/groupfeatures.py
> +        self._musicclass = res['queue_musicclass']
This fix need to be documented in another ticket.

2024-02-21 13:15 UTC, closed without merging